### ISSUE TITLE
chrome 拡張機能を実行できるようにする

### ISSUE THREAD

**Issue by siriusu** [siriusu/chrome_extension_test#6]
## 概要
chrome 拡張機能を実行できるようにする

## TODO
- [ ] 拡張機能が実行できる状態にする
  - [ ] manifest.json を準備する
  - [ ] popup.html をエントリとして準備する
  - [ ] ブラウザのアイコンをクリックして起動できるようにする
  - [ ] console.log でデバッグできることを確認する
